### ISSUE TITLE
Add class for CloudWatch Logs Metric Filter

### ISSUE THREAD

**Issue by markuman** [mattclay/aws-terminator#75]
Ansible Pull Request: https://github.com/ansible/ansible/pull/59925  
The integration test failed with an `AccessDeniedException` in https://app.shippable.com/github/ansible/ansible/runs/149823/113/console  
The integration test creates one CloudWatch log group and applies metric filters on it.

**Comment by markuman** [comment]
The existing policy needs to be append.

https://github.com/mattclay/aws-terminator/blob/master/aws/policy/application-services.yaml#L161

The integration tests needs also

* `logs:DescribeMetricFilter`
* `logs:PutMetricFilter`
* `logs:DeleteMetricFilter`

**Comment by markuman** [comment]
@jillr @mattclay 
step 1 https://github.com/markuman/aws-terminator/commit/1846b9af8a179392b1bf73a25fbd71fae2eba369

but I'm not sure if this is necessary. If I delete a log group, the applied metric filter will automatically removed too?

**Comment by jillr** [comment]
@markuman  That makes sense, I just don't see anything in the boto or api docs to that effect so I assumed metrics would need a class to do clean up. I'll probably need to just experiment with it to confirm metrics clean up properly with log groups when I review the PR.  Thanks.

**Comment by markuman** [comment]
Sorry for the late reply, currently my time is rare with a newborne.

````
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: create new cloudwatch log group
      cloudwatchlogs_log_group:
        log_group_name: "ansible_test_group"
        retention: 1

    - name: apply metric filter on cwl group
      cloudwatchlogs_log_group_metric_filter:
        log_group_name: ansible_test_group
        filter_name: ansible_filter
        filter_pattern: "some pattern"
        state: present
        metric_transformation:
          metric_name: some_pattern_count
          metric_namespace: ansible_metrics
          metric_value: "1"

    - name: delete log group
      cloudwatchlogs_log_group:
        log_group_name: "ansible_test_group"
        state: absent

    - name: is it really gone?
      cloudwatchlogs_log_group:
        log_group_name: "ansible_test_group"
        state: absent
```

When I execute this:

```
PLAY [localhost] *********************************************************************************************************************************************************************

TASK [create new cloudwatch log group] ***********************************************************************************************************************************************
changed: [localhost]

TASK [apply metric filter on cwl group] **********************************************************************************************************************************************
changed: [localhost]

TASK [delete log group] **************************************************************************************************************************************************************
changed: [localhost]

TASK [is it really gone?] ************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

The log group is gone, and with it its metric filter.  
So I'm not sure if the terminator class for CloudWatch Logs https://github.com/mattclay/aws-terminator/blob/master/aws/terminator/application_services.py#L30 is already sufficient?  
@jillr @mattclay
